# -*- coding: utf-8 -*-
"""project_work_emiliano_acerra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PVL3EeQIIAx-9ek7NSNSdabLWiKH_xQd

## 1. Funzione per l'analisi delle performance individuali dei piloti

Iniziamo importando il csv all'interno del foglio di lavoro. Tramite la funzione "DictReader", è possibile leggere le stringhe del dataset come fossero dei dizionari.
"""

import csv

with open("formula1_data.csv") as csv_file: # Apriamo il file con la funzione "open". Non è necessario specificare nessuna lettera perché ci serve la sola lettura del file
        dataset=csv.DictReader(csv_file)


        for row in dataset:
          print(row)

"""La prima richiesta è quella di fornire una panoramica sui risultati individuali dei piloti, in particolare i punti totali (rispettando un certo critertio di asssegnazione), le vittorie dei Gran Premi e i podi di ciascun pilota. Iniziamo estraendo la lista dei piloti."""

with open("formula1_data.csv") as csv_file:
        dataset=csv.DictReader(csv_file)

        drivers_list=[] # Creiamo una lista vuota e, tramite un ciclo che itera sul dataset, estraiamo i nomi dei piloti

        for row in dataset:
          if row["Driver"] not in drivers_list:
            drivers_list.append(row["Driver"])

drivers_list

"""Creiamo ora 3 dizionari, che conterranno punti, podi e vittorie dei singoli piloti"""

driver_points= {driver: 0 for driver in drivers_list} # Le chiavi sono i piloti e i valori i punteggi totali. Inizializziamo i valori a zero
driver_victories= {driver: 0 for driver in drivers_list} # Le chiavi sono i piloti e i valori le vittorie totali. Inizializziamo i valori a zero
driver_podiums= {driver: 0 for driver in drivers_list} # Le chiavi sono i piloti e i valori i podi totali. Inizializziamo i valori a zero

"""Ora è il momento di calcolare i punteggi e inserirli nei vari dizionari. Iniziamo col calcolo del puinteggio totale. Per farlo, creiamo un ciclo che itera sulle righe del dataset e calcola i punteggi secondo i criteri che ci sono stati forniti"""

with open("formula1_data.csv") as csv_file:
        dataset=csv.DictReader(csv_file)

        for row in dataset:                               # Iteriamo sulle righe
                driver=row["Driver"]
                if driver in driver_points:               # Controlliamo che il pilota sia nella nostra lista
                    if row["Position"]=="1":              # calcoliamo i punti
                        driver_points[driver] += 10
                    elif row["Position"]=="2":
                        driver_points[driver] += 8
                    elif row["Position"]=="3":
                        driver_points[driver] += 6
                    elif row["Position"]=="4":
                        driver_points[driver] += 5
                    elif row["Position"]=="5":
                        driver_points[driver] += 4
                    elif row["Position"]=="6":
                        driver_points[driver] += 3
                    elif row["Position"]=="7":
                        driver_points[driver] += 2
                    elif row["Position"]=="8":
                        driver_points[driver] += 1
                    else:
                        driver_points[driver] += 0

driver_points

"""Facciamo lo stesso con le vittorie"""

with open("formula1_data.csv") as csv_file:
        dataset=csv.DictReader(csv_file)

        for row in dataset:
                driver=row["Driver"]
                if driver in driver_victories:
                    if row["Position"]=="1":
                        driver_victories[driver] += 1
driver_victories

"""Infine, con i podi"""

with open("formula1_data.csv") as csv_file:
        dataset=csv.DictReader(csv_file)

        for row in dataset:
                driver=row["Driver"]
                if driver in driver_podiums:
                    if "1"<=row["Position"]<="3":
                        driver_podiums[driver] += 1

driver_podiums

"""Ora, chiedendo in input un pilota, viene stampata una lista contentente il numero di punti totali, di vittore e di podi che abbiamo calcolato. Utilizziamo un assert che serva in caso in cui il nome inserito non sia valido."""

request= input("Inserisci il nome del pilota: ").strip().title()  # Con questi comandi uniformiamo le maiuscole ed eventuali spazi

assert request in drivers_list, "Nome inserito non valido"

print([driver_points[request],driver_victories[request],driver_podiums[request]])

"""## 2. Funzione per la creazione della classifica finale dei piloti

Il dizionario driver_points contiene già i punteggi totali dei piloti.
"""

print(driver_points)

"""Apriamo ora un nuovo file di testo per contenere queste informazioni."""

with open("Drivers_Standings_2008.txt", "a") as new_file:  # In questo caso apro in modalità lettura e scrittura, inserendo l'indice "a"
    new_file.write("Drivers Standings 2008 Formula \n")    # Intestazione all'interno del file
    for driver, score in driver_points.items():            # Ciclo per inserire i dati richiesti
        new_file.write(f"{driver}: {score}\n")

"""## 3. Funzione per la classifica dei costruttori

Per creare una classifica dei costruttori, iniziamo con una lista che contiene tutti i team presenti nel dataset
"""

with open("formula1_data.csv") as csv_file:
        dataset=csv.DictReader(csv_file)

        team_list=[]
        for row in dataset:
            if row["Team"] not in team_list:
                team_list.append(row["Team"])

print(team_list)

"""Creiamo un dizionario che contiene i nomi dei costruttori e il loro punteggio totale"""

team_points={team:0 for team in team_list}  # Inizializziamo il punteggio a 0
team_points

"""Per concludere, come fatto in precedenza, creiamo un ciclo che itera sulla righe del dataset e calcola i punteggi di ciascun team in base ai criteri dati.

"""

with open("formula1_data.csv") as csv_file:
        dataset=csv.DictReader(csv_file)

        for row in dataset:
                team=row["Team"]
                if team in team_points:
                    if row["Position"]=="1":
                        team_points[team] += 10
                    elif row["Position"]=="2":
                        team_points[team] += 8
                    elif row["Position"]=="3":
                        team_points[team] += 6
                    elif row["Position"]=="4":
                        team_points[team] += 5
                    elif row["Position"]=="5":
                        team_points[team] += 4
                    elif row["Position"]=="6":
                        team_points[team] += 3
                    elif row["Position"]=="7":
                        team_points[team] += 2
                    elif row["Position"]=="8":
                        team_points[team] += 1
                    else:
                        team_points[team] += 0

team_points